export {default as HomeIcon} from './Icon/Home';
export {default as ApplePay} from "../_atoms/Icon/pay/ApplePay"
export {default as VisaPay} from "../_atoms/Icon/pay/VisaPay"
export {default as DiscoverPay} from "../_atoms/Icon/pay/DiscoverPay"
export {default as MastercardPay} from "../_atoms/Icon/pay/MastercardPay"
export {default as SecurePay} from "../_atoms/Icon/pay/SecurePay"
export {default as FacebookIcon} from "../_atoms/Icon/Facebook"
export {default as InstagramIcon} from "./Icon/InstagramIcon"
export {default as ProductCart} from "./Icon/ProductCart"
export {default as DownArrow} from "../_atoms/Icon/arrows/DownArrow"
export { default as UpArrow } from "../_atoms/Icon/arrows/UpArrow"
export { default as PinIcon } from "./Icon/HeaderIcon/Pin"
export { default as ArrowIcon } from "./Icon/HeaderIcon/Arrow"
export { default as EcoBazarIcon } from "./Icon/HeaderIcon/EcoBazar"
export { default as HeartIcon } from "./Icon/HeaderIcon/Heart"
export {default as BagIcon} from "./Icon/HeaderIcon/Bag"